import socket
import struct
import json
import os
import numpy as np
import pickle
import sys


PORT = 50423

PeriodicTable = ["H","He","Li","Be","B","C","N","O","F","Ne","Na","Mg","Al","Si","P","S","Cl","Ar","K","Ca","Sc","Ti","V","Cr","Mn","Fe","Co","Ni","Cu","Zn","Ga","Ge","As","Se","Br","Kr","Rb","Sr","Y","Zr","Nb","Mo","Tc","Ru","Rh","Pd","Ag","Cd","In","Sn","Sb","Te","I","Xe","Cs","Ba","La","Ce","Pr","Nd","Pm","Sm","Eu","Gd","Tb","Dy","Ho","Er","Tm","Yb","Lu","Hf","Ta","W","Re","Os","Ir","Pt","Au","Hg","Tl","Pb","Bi","Po","At","Rn","Fr","Ra","Ac","Th","Pa","U","Np","Pu","Am","Cm","Bk","Cf","Es","Fm","Md","No","Lr","Rf","Db","Sg","Bh","Hs","Mt","Ds","Rg","Cn","Nh","Fl","Mc","Lv","Ts","Og"]

bohr2angstrom = 0.529177249
angstrom2bohr = 1.0/bohr2angstrom
ev2hartree = 0.036749322


def send_calculation_job(sock, xyz_content, charge, multiplicity, calc_type):

    metadata = {
        "filename": "mol", "charge": charge,
        "multiplicity": multiplicity, "calc_type": calc_type,
    }
    header_bytes = json.dumps(metadata).encode('utf-8')
    payload_bytes = xyz_content.encode('utf-8')
    sock.sendall(struct.pack('Q', len(header_bytes)))
    sock.sendall(header_bytes)
    sock.sendall(struct.pack('Q', len(payload_bytes)))
    sock.sendall(payload_bytes)
    print("Sent job to server.")
    return True


def recvall(sock, n):
    data = bytearray()
    while len(data) < n:
        packet = sock.recv(n - len(data))
        if not packet: return None
        data.extend(packet)
    return data

def recv_object(sock): 
    raw_msglen = recvall(sock, 8)
    if not raw_msglen: return None
    msglen = struct.unpack('Q', raw_msglen)[0]
    
    data = recvall(sock, msglen)
    obj = pickle.loads(data)
    return obj

def save_result(result, output_file, calctype):
    if calctype == 0:  # energy
        with open(output_file, 'w') as f:
            energy = result["energy"]
            #energy, dipole-moment (xyz)	    	E, Dip(I), I=1,3	    	4D20.12
            f.write(f"{energy:20.12e}{0:20.12e}{0:20.12e}{0:20.12e}\n")
    elif calctype == 1:  # force
        with open(output_file, 'w') as f:
            energy = result["energy"]
            forces = result["forces"]
            #energy, dipole-moment (xyz)	    	E, Dip(I), I=1,3	    	4D20.12
            f.write(f"{energy:20.12e}{0:20.12e}{0:20.12e}{0:20.12e}\n") 
            #gradient on atom (xyz)	    	FX(J,I), J=1,3; I=1,NAtoms	    	3D20.12
            for i in range(len(forces)):
                f.write(f"{forces[i,0]:20.12e}{forces[i,1]:20.12e}{forces[i,2]:20.12e}\n".replace('e', 'E'))
    elif calctype == 2:  # hessian
        with open(output_file, 'w') as f:
            energy = result["energy"]
            forces = result["forces"] 
            hessian = result["hessian"]
            #energy, dipole-moment (xyz)	    	E, Dip(I), I=1,3	    	4D20.12
            f.write(f"{energy:20.12e}{0:20.12e}{0:20.12e}{0:20.12e}\n") 
            #gradient on atom (xyz)	    	FX(J,I), J=1,3; I=1,NAtoms	    	3D20.12
            for i in range(len(forces)):
                f.write(f"{forces[i,0]:20.12e}{forces[i,1]:20.12e}{forces[i,2]:20.12e}\n".replace('e', 'E'))
            #polarizability		Polar(I), I=1,6		3D20.12
            for i in range(2):
                f.write(f"{0:20.12e}{0:20.12e}{0:20.12e}\n".replace('e', 'E'))
            #dipole derivatives		DDip(I), I=1,9*NAtoms		3D20.12
            for i in range(3*len(forces)):
                f.write(f"{0:20.12e}{0:20.12e}{0:20.12e}\n".replace('e', 'E'))
            #force constants		FFX(I), I=1,(3*NAtoms*(3*NAtoms+1))/2		3D20.12
            #the Hessian is given in lower triangular form: αij, i=1 to N, j=1 to i. 
            num_coords = hessian.shape[0]
            triangle_indices = np.tril_indices(num_coords)
            hessian_lower = hessian[triangle_indices]
            for i in range(0, len(hessian_lower), 3):
                row = hessian_lower[i:i+3]
                while len(row) < 3:
                    row = np.append(row, 0.0)
                f.write(f"{row[0]:20.12e}{row[1]:20.12e}{row[2]:20.12e}\n".replace('e', 'E'))
                #f.write(f"{1:20.12e}{1:20.12e}{1:20.12e}\n".replace('e', 'D'))

# --- 主函数 ---
def main():
    input_file = sys.argv[2]
    output_file = sys.argv[3]

    calctyp_dict = {0: "energy", 1: "force", 2: "hessian"}
    with open(input_file, 'r') as f:
        lines = f.readlines()
        NUM_ATOM = int(lines[0].split()[0])
        calctype = int(lines[0].split()[1])
        calctype_str = calctyp_dict.get(calctype, "energy")
        charge = int(lines[0].split()[2])
        multiplicity = int(lines[0].split()[3])
        Geom = np.zeros((NUM_ATOM, 3))
        Elements = []
        for i in range(1, NUM_ATOM + 1):
            line = lines[i].split()
            Elements.append(PeriodicTable[int(line[0]) - 1])
            for j in range(1, 4):
                Geom[i-1, j-1] = float(line[j])

    xyz_content = f"{NUM_ATOM}\nGenerated by client\n"
    for i in range(NUM_ATOM):
        xyz_content += f"{Elements[i]} {Geom[i,0]*bohr2angstrom} {Geom[i,1]*bohr2angstrom} {Geom[i,2]*bohr2angstrom}\n"
    
    server_address = ('localhost', PORT)
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.connect(server_address)
        
        if send_calculation_job(sock, xyz_content, charge, multiplicity, calctype_str):
            result = recv_object(sock)
            if result is None:
                return
        else:
            return
        print("Received result from server:")
        print(f"SCF Done:  E(UMA) =  {result['energy']}     A.U.")
        #close the connection
        sock.close()

    save_result(result, output_file, calctype)



if __name__ == "__main__":
    main()

